import { z } from 'zod';

export const TypeOfTransactionSchema = z.enum(['DEPOSIT','WITHDRAWAL','BET','WIN','TRANSFER_SENT','TRANSFER_RECEIVED','SYSTEM_ADJUSTMENT_CREDIT','SYSTEM_ADJUSTMENT_DEBIT','TOURNAMENT_BUYIN','TOURNAMENT_PRIZE','AFFILIATE_COMMISSION','REFUND','FEE','BONUS_AWARD','BET_PLACE','BET_WIN','BET_LOSE','BET_REFUND','BONUS_WAGER','BONUS_CONVERT','BONUS_EXPIRED','XP_AWARD','ADJUSTMENT_ADD','ADJUSTMENT_SUB','INTERNAL_TRANSFER','PRODUCT_PURCHASE','REBATE_PAYOUT','JACKPOT_WIN','JACKPOT_CONTRIBUTION']);

export type TypeOfTransactionType = `${z.infer<typeof TypeOfTransactionSchema>}`

export default TypeOfTransactionSchema;
